[package]
name = "asynch_bt"
version = "0.1.0"
authors = ["nilsb"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
clap = "2.32.0"
lalrpop-util = "0.16.2"
regex = "0.2.1"
quote = "0.6"
proc-macro2 = "0.4"
